name: rcsend
description: A Dart script to send messages via Google Messages using Puppeteer
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  puppeteer: ^3.13.0
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
